# Generated by Django 4.1.2 on 2022-10-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                ("flg", models.BooleanField()),
            ],
            options={"verbose_name": "Ambiente", "verbose_name_plural": "Ambientes",},
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                ("flg", models.BooleanField()),
            ],
            options={"verbose_name": "Grupo", "verbose_name_plural": "Grupos",},
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                ("flg", models.BooleanField()),
            ],
            options={
                "verbose_name": "Localizaçõa",
                "verbose_name_plural": "Localizações",
            },
        ),
        migrations.CreateModel(
            name="Secao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                ("flg", models.BooleanField()),
            ],
            options={"verbose_name": "Seção", "verbose_name_plural": "Seções",},
        ),
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=50)),
                ("unidadeMedida", models.CharField(max_length=15)),
                ("flg", models.BooleanField()),
            ],
            options={
                "verbose_name": "UnidadeMedida",
                "verbose_name_plural": "UnidadeMedidas",
                "db_table": "estoque_unidademedida",
            },
        ),
        migrations.CreateModel(
            name="SubGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idGrupo", models.PositiveIntegerField()),
                ("descricao", models.CharField(max_length=70)),
                ("flg", models.BooleanField()),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="estoque.grupo"
                    ),
                ),
            ],
            options={"verbose_name": "SubGrupo", "verbose_name_plural": "SubGrupos",},
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoBarra", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("precoCusto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("percentual", models.DecimalField(decimal_places=2, max_digits=5)),
                ("precoVenda", models.DecimalField(decimal_places=2, max_digits=8)),
                ("lote", models.CharField(max_length=30)),
                (
                    "quantidadeDisponivel",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "quantidadeMinima",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "quantidadeMaxima",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("pesoLiquido", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pesoBruto", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "temperaturaMinima",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "temperaturaMaxima",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("perecivel", models.BooleanField()),
                ("promocao", models.BooleanField()),
                ("precoPromocao", models.DecimalField(decimal_places=2, max_digits=8)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("observacao", models.CharField(max_length=150)),
                ("flg", models.BooleanField()),
                ("ipi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("icms", models.DecimalField(decimal_places=2, max_digits=5)),
                ("aliquota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("consignacao", models.BooleanField()),
                (
                    "tipoIncendio",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "CLASSE A"),
                            (2, "CLASSE B"),
                            (3, "CLASSE C"),
                            (4, "CLASSE D"),
                        ]
                    ),
                ),
                ("fabricanteT", models.CharField(max_length=80)),
                ("fornecedorT", models.CharField(max_length=80)),
                ("unidadeMed", models.CharField(max_length=15)),
                ("ambienteT", models.CharField(max_length=70)),
                ("secaoT", models.CharField(max_length=70)),
                ("localizacaoT", models.CharField(max_length=70)),
                ("grupoT", models.CharField(max_length=70)),
                ("subGrupoT", models.CharField(max_length=70)),
                (
                    "ambiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.ambiente",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="estoque.grupo"
                    ),
                ),
                (
                    "localizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.localizacao",
                    ),
                ),
                (
                    "secao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="estoque.secao"
                    ),
                ),
                (
                    "subgrupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.subgrupo",
                    ),
                ),
                (
                    "unidadeMedida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.unidademedida",
                    ),
                ),
            ],
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos",},
        ),
    ]
